setup :
	ln -s ../data/* .
	ln -s ../src/pntmatcher .
	ln -s ../src/pntmatcher pntmatcher_rs
	ln -s ../src/pntmatcher ransac
	ln -s ../src/pntmatcher iransac


clean :
	rm -f *.prb
	rm -f *.pnt
	rm -f *.pgm
	rm -rf results_*/
	rm -f pntmatcher
	rm -f ransac
	rm -f iransac
	rm -f pntmatcher_rs
